/// Defines and implements a conformance to the ``Table`` protocol.
@attached(
  extension,
  conformances: Table,
  PrimaryKeyedTable,
  names: named(Columns),
  named(Draft),
  named(columns),
  named(init(_:)),
  named(init(decoder:)),
  named(tableName)
)
@attached(
  memberAttribute
)
public macro Table(_ name: String? = nil) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "TableMacro"
  )

/// Customizes a column generated by the ``Table`` protocol.
///
/// - Parameters:
///   - name: The column's name.
///   - representableType: A type that represents the property type in a query expression. For types
///     that don't have a single representation in SQL, like `Date` and `UUID`.
///   - primaryKey: The column is its table's auto-incrementing primary key.
@attached(accessor, names: named(willSet))
public macro Column(
  _ name: String? = nil,
  as representableType: (any QueryRepresentable.Type)? = nil,
  primaryKey: Bool = false
) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "ColumnMacro"
  )

@attached(
  memberAttribute
)
@attached(
  extension,
  conformances: Table,
  names: named(Columns),
  named(columns),
  named(init(_:)),
  named(init(decoder:)),
  named(tableName)
)
public macro _Draft<T: Table>(_: T.Type) =
  #externalMacro(
    module: "StructuredQueriesMacros",
    type: "TableMacro"
  )
