//import IssueReporting

// TODO: Rename to Schema
//       Nested type generated by macro also called Schema
//       Rename allColumns to columns
public protocol Schema<QueryOutput>: QueryExpression where QueryOutput: Table {
  var allColumns: [any ColumnExpression<QueryOutput>] { get }
}

extension Schema {
  public var queryFragment: QueryFragment {
    allColumns.map(\.queryFragment).joined(separator: ", ")
  }

  // TODO: Should we keep this?
  //       If so, make more efficient with OrderedDictionary and perhaps get rid of force unwrap.
  public func column<Member>(for keyPath: KeyPath<QueryOutput, Member>) -> Column<QueryOutput, Member>? {
    for column in allColumns {
      if column.keyPath == keyPath {
        return (column as! Column<QueryOutput, Member>)
      }
    }
    return nil
  }
}

#if canImport(Foundation)
  import Foundation
  extension Schema {
    // TODO: Make efficient with orded dictionary
    public func sort(
      by keyPathComparator: KeyPathComparator<QueryOutput>
    ) -> some QueryExpression<Bool> {
      for column in allColumns {
        if column.keyPath == keyPathComparator.keyPath {
          return _KeyPathComparatorExpression(columnsAndOrders: [(column, keyPathComparator.order)])
        }
      }
//      reportIssue(
//        """
//        Could not find column for key path '\(keyPathComparator.keyPath)'. This is only supported \
//        for  key paths of stored properties.
//        """
//      )
      fatalError(
        """
        Could not find column for key path '\(keyPathComparator.keyPath)'. This is only supported \
        for  key paths of stored properties.
        """
      )
    }

    public func sort(
      by keyPathComparators: [KeyPathComparator<QueryOutput>]
    ) -> some QueryExpression<Bool> {
      let columnsAndOrders = keyPathComparators.compactMap { keyPathComparator in
        for column in allColumns {
          if column.keyPath == keyPathComparator.keyPath {
            return (column, keyPathComparator.order)
          }
        }
//        reportIssue(
//          """
//          Could not find column for key path '\(keyPathComparator.keyPath)'. This is only supported \
//          for  key paths of stored properties.
//          """
//        )
        fatalError(
          """
          Could not find column for key path '\(keyPathComparator.keyPath)'. This is only \
          supported for  key paths of stored properties.
          """
        )
      }
      return _KeyPathComparatorExpression(columnsAndOrders: columnsAndOrders)
    }
  }

  private struct _KeyPathComparatorExpression<Table>: QueryExpression {
    typealias QueryOutput = Bool
    let columnsAndOrders: [(any ColumnExpression<Table>, SortOrder)]

    var queryFragment: QueryFragment {
      columnsAndOrders
        .map { "\(bind: $0) \(raw: $1 == .forward ? "ASC" : "DESC")" }
        .joined(separator: ", ")
    }
  }
#endif

// db.addColumn(SyncUp.schema.isActive.name

import SwiftData

@available(macOS 14, *)
@Model
class SyncUp {
  var id: Int
  var name: String
  var isActive: Bool
  init(id: Int, name: String, isActive: Bool) {
    self.id = id
    self.name = name
    self.isActive = isActive
  }
}
